version: "3.8"

services:
  elasticsearch:
    image: elasticsearch:8.5.0
    container_name: es-core
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200" 
    networks:
      - elk
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  logstash:
    image: logstash:8.5.0
    container_name: ls-core
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"  
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    networks:
      - elk
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  kibana:
    image: kibana:8.5.0
    container_name: kb-core
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601" 
    networks:
      - elk
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  elk:
    driver: bridge
#    internal: true  This prevents external access, remove if needed for localhost

