services:
  elasticsearch:
    image: elasticsearch:${STACK_VERSION}
    container_name: es-core
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "${ES_PORT}:9200"
    networks:
      - elk
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  logstash:
    image: logstash:${STACK_VERSION}
    container_name: ls-core
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"
      - "1514:1514/udp"  # For Wazuh alerts
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    networks:
      - elk
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  kibana:
    image: kibana:${STACK_VERSION}
    container_name: kb-core
    depends_on:
      - elasticsearch
    ports:
      - "${KIBANA_PORT}:5601"
    networks:
      - elk
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  wazuh-manager:
    image: wazuh/wazuh-manager:4.12.0
    container_name: wazuh-manager
    ports:
      - "1515:1515"         # Wazuh cluster communication (TCP)
      - "55000:55000"       # Wazuh API
      - "1514:1514/udp"     # Wazuh syslog port (UDP)
    environment:
      - WAZUH_CLUSTER_NAME=wazuh-cluster
      - WAZUH_ENABLE_API=yes
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge
