version: "3.8"

services:
  elasticsearch:
    image: elasticsearch:8.5.0
    container_name: es-core
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks:
      - elk
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  logstash:
    image: logstash:8.5.0
    container_name: ls-core
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    networks:
      - elk
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  kibana:
    image: kibana:8.5.0
    container_name: kb-core
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - elk
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  wazuh:
    image: wazuh/wazuh:3.13.6_7.9.2
    container_name: wazuh-manager
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "55000:55000"
    environment:
      - WAZUH_CLUSTER_NAME=wazuh-cluster
      - WAZUH_ENABLE_API=yes
    networks:
      - elk
    depends_on:
      - elasticsearch

  web:
    image: nginx:alpine
    container_name: web-victim
    ports:
      - "8080:80"
    networks:
      - elk
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  elk:
    driver: bridge
