version: "3.8"

services:
  elasticsearch:
    image: elasticsearch:8.5.0
    container_name: es-core
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200" 
    networks:
      - elk
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  logstash:
    image: logstash:8.5.0
    container_name: ls-core
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"  
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    networks:
      - elk
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  kibana:
    image: kibana:8.5.0
    container_name: kb-core
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601" 
    networks:
      - elk
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  wazuh-manager:
    image: wazuh/wazuh-manager:4.12.0
    container_name: wazuh-manager
    ports:
      - "1515:1515"         # Wazuh cluster communication (TCP)
      - "55000:55000"       # Wazuh API
      - "1514:1514/udp"     # Wazuh syslog port (UDP)
    environment:
      - WAZUH_CLUSTER_NAME=wazuh-cluster
      - WAZUH_ENABLE_API=yes
    networks:
      - elk
    depends_on:
      - elasticsearch
  wazuh-agent:
    image: kennyopennix/wazuh-agent:4.11.1
    container_name: wazuh-agent
    environment:
      - WAZUH_MANAGER=wazuh-manager
      - WAZUH_REGISTRATION_SERVER=wazuh-manager
    volumes:
      - /:/host
      - /var/log:/var/log
    privileged: true
    networks:
      - elk
    depends_on:
      - wazuh-manager

  nginx:
    image: nginx:latest
    container_name: nginx-web
    ports:
      - "80:80"
    networks:
      - elk
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
networks:
  elk:
    driver: bridge
#    internal: true  This prevents external access, remove if needed for localhost
