name: Docker CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate Docker Compose file
        run: docker-compose -f docker-compose.yml config

      - name: Build Docker services
        run: docker-compose -f docker-compose.yml build
